### ISSUE TITLE
Support JS-WISPApi [Idea]

### ISSUE THREAD

**Issue by MikkelDK** [Linux123123/JSPteroAPI#46]
**Is your feature request related to a problem? Please describe.**
Problem with suspending a test-server from your discord-bot.
- Bot can't suspend the ID 2854380a (because it doesn't read the ID as number/letter - so BOT is trying to suspend ``2854380`` and it should suspend the ``2854380a`` which it can't since API are the diff between pterodactyl & WISP.
```
[2021-08-13 14:15:56]: CMD Server Owner mrc4t (249229859824467969) ran command suspend
[2021-08-13 14:15:56]: ERROR An error has accured: Error
JSPteroAPIError
at Request.request (/home/container/node_modules/@linux123123/jspteroapi/dist/application/ApplicationRequest.js:35:19)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async Object.run (/home/container/dist/commands/suspend.js:8:21) {
HTML_URL: 'https://cp.lindhost.eu/api/client/servers/2854380/suspend',
```

**Describe the solution you'd like**
Make JSPteroAPI to supporting WISP.gg's API (or make separate GitHub/node_modules for that.

**Describe alternatives you've considered**
Support WISP.gg API (e.g)

**Additional context**
_I'm willing to pay for it could be possible (I can pay at PayPal)_

**Comment by Linux123123** [comment]
Thanks for reporting.

I haven't thought to support `wisp` as I though that they share the same API with `pterodactyl`. I will test it out and see what are the changes.

As for supporting me I have my `paypal` in my profile description.

**Comment by Linux123123** [comment]
Well I can't really test the API (as I don't have the wisp panel) and I can't find the API docs.

**Comment by MikkelDK** [comment]
@Linux123123 Sorry I forgot to link it =) https://docs.panel.gg/#introduction it's there.

**Comment by Linux123123** [comment]
The link you sent me only has the client API docs. For the suspend command I need the admin API.

**Comment by MikkelDK** [comment]
https://dashflo.net/docs/api/pterodactyl/v0.7/#introduction < there. ^^ they using 0.7

**Comment by Linux123123** [comment]
The ID's are still numbers. I guess that is not related to the API changes at all. You just need to use the ID numbers from admin area instead of UUID. That is an API limitation as you can't suspend server with `UUID`. It is possible to find the internal ID by the UUID, but that would be another request before the request to suspend.

Basically you press on the server you want to suspend and You will see it's internal identifier. 
![image](https://user-images.githubusercontent.com/26341983/129399646-7596e2bd-76e7-4740-9618-f44cd6fdf742.png)
![image](https://user-images.githubusercontent.com/26341983/129399728-0fe63eb8-3920-4599-be8c-4e90f15245a0.png)

**Comment by MikkelDK** [comment]
Oh.

So it's not possible to get a "list" of the Internal ID from your discord-bot script?

**Comment by Linux123123** [comment]
Yes it is possible. The `!servers` command gives the server identifier.

**Comment by MikkelDK** [comment]
> Yes it is possible. The `!servers` command gives the server identifier.

Just weird, it does not show. o_0
Trying to msg ``!server 60``
![](https://pic.lindhost.eu/bo86B5eiJ4.png)
BOT:
![](https://pic.lindhost.eu/ceXw9bvcn4.png)

the ID 60:
![](https://pic.lindhost.eu/O94NE9y1Mk.png)

**Comment by Linux123123** [comment]
Yeah that is a bug. I will close this for now. Expect a new version of the bot.
