### ISSUE TITLE
I have problems updating the some parameters inside envioronment

### ISSUE THREAD

**Issue by thevisuales** [Linux123123/JSPteroAPI#48]
`app.editServerStartup(idserverpanel, {
    environment: {
      WORLD_SIZE: '1000',
      WORLD_SEED: '3434',
    },
  }).then((res) => console.log(res))
`

Hi, I've been looking at some examples and I think the structure is correct. However I get the following error:

`...\node_modules\@linux123123\jspteroapi\dist\application\ApplicationRequest.js:36
            return this.errorHandler(new Error_1.JSPteroAPIError(rawData, await rawData.json(), data, requestType));
                                     ^

JSPteroAPIError
    at Application.request (......\node_modules\@linux123123\jspteroapi\dist\application\ApplicationRequest.js:36:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  HTML_URL: 'https://myserver.com/api/application/servers/43/startup$',
  HTML_STATUS: 405,
  HTML_STATUS_TEXT: 'Method Not Allowed',
  REQUEST_TYPE: 'PATCH',
  REQUEST_BODY: {
    startup: './RustDedicated -batchmode +server.port {{SERVER_PORT}} +server.identity "rust" +rcon.port {{RCON_PORT}} +rcon.web true +server.hostname \\"{{HOSTNAME}}\\" +server.level \\"{{LEVEL}}\\" +server.description \\"{{DESCRIPTION}}\\" +server.url \\"{{SERVER_URL}}\\" +server.headerimage \\"{{SERVER_IMG}}\\" +server.logoimage \\"{{SERVER_LOGO}}\\" +server.worldsize \\"{{WORLD_SIZE}}\\" +server.seed \\"{{WORLD_SEED}}\\" +server.maxplayers {{MAX_PLAYERS}} +rcon.password \\"{{RCON_PASS}}\\" +server.saveinterval {{SAVEINTERVAL}} +app.port {{APP_PORT}} {{ADDITIONAL_ARGS}}',
    environment: {
      HOSTNAME: 'A Rust Server',
      OXIDE: '0',
      LEVEL: 'Procedural Map',
      DESCRIPTION: 'Powered by Pterodactyl',
      SERVER_URL: 'https://google.com',
      WORLD_SIZE: '1000',
      WORLD_SEED: '3434',
      MAX_PLAYERS: '40',
      RCON_PORT: '28016',
      RCON_PASS: 'CHANGEME',
      SAVEINTERVAL: '60',
      APP_PORT: '28082'
    },
    egg: 14,
    image: 'quay.io/pterodactyl/core:rust',
    skip_scripts: undefined
  },
  ERRORS: [
    'The PATCH method is not supported for this route. Supported methods: DELETE.'
  ]
}`

I would appreciate someone to tell me where I am failing. I also got another bug before but have managed to patch it. He told me:
Error: Environment variable SERVER_IMG was not defined!

When that parameter is empty by default and I don't want to overwrite it.

**Comment by thevisuales** [comment]
Ok after doing some research I discovered that there was a **$** left over.
https://github.com/Linux123123/JSPteroAPI/blob/ffd90ffddc7907ff954fbaeb5f87881179c16d5c/src/application/methods/serverMethods.ts#L255

And this is what I had to comment on to make it work for me.
https://github.com/Linux123123/JSPteroAPI/blob/ffd90ffddc7907ff954fbaeb5f87881179c16d5c/src/application/methods/serverMethods.ts#L238

**Comment by Linux123123** [comment]
> Ok after doing some research I discovered that there was a **$** left over.
> https://github.com/Linux123123/JSPteroAPI/blob/ffd90ffddc7907ff954fbaeb5f87881179c16d5c/src/application/methods/serverMethods.ts#L255

So this is indeed a leftover **$** which I will fix.

> And this is what I had to comment on to make it work for me.
> https://github.com/Linux123123/JSPteroAPI/blob/ffd90ffddc7907ff954fbaeb5f87881179c16d5c/src/application/methods/serverMethods.ts#L238

But I am not sure about this error. It checks if the provided variable is supported by the egg. It grabs the egg information and checks if it can be used.

![image](https://user-images.githubusercontent.com/26341983/133785753-3ca6fa13-9669-4641-be7c-af82bacc0d73.png)

So the egg includes `nullable` in rules, so this should grab it and send it as empty.
https://github.com/Linux123123/JSPteroAPI/blob/ffd90ffddc7907ff954fbaeb5f87881179c16d5c/src/application/methods/serverMethods.ts#L317

I will test it locally.

**Comment by Linux123123** [comment]
Ok I found the issue and fixed it in the `next` branch. It will be released sometime today.
