### ISSUE TITLE
[BUG] API can never find an API key.

### ISSUE THREAD

**Issue by Timtendo12** [Linux123123/JSPteroAPI#53]
**Describe the bug**
API says client Token is invalid even tho its right?

**To Reproduce**
1. Go to Application API on your panel
2. Click on 'create new'
3. Permissions ( Everything on read)
4. Copy API in a .json file and call it using `${config.PteroToken}`

**Expected behavior**
I expected the API to succesfully connect with my API without giving it a error.

**Screenshots**
![image](https://user-images.githubusercontent.com/41442518/145580817-cf0064ad-181c-4671-a8e7-3e6cb22c324b.png)

![image](https://user-images.githubusercontent.com/41442518/145580940-d6662521-f87b-4804-b50f-7103db38a635.png)

![Screenshot from 2021-12-10 14-25-33](https://user-images.githubusercontent.com/41442518/145581353-a6a67e53-07e9-422c-aca6-a4c97c36370c.png)

**Comment by Timtendo12** [comment]
Issue is fixed. After some extra digging around I found out there is a different between Application and Client. I've found where to get the Client key and now it works! A oopsie woopsie from my side!

**Comment by Linux123123** [comment]
No problem :). Great to hear that it worked at the end
