### ISSUE TITLE
'node-fetch' module causes errors in project when building

### ISSUE THREAD

**Issue by ararouu** [Linux123123/JSPteroAPI#75]
Whenever I try to build my project, I get these errors, any help would be appreciated!
Info:
Yarn v1.22.19
TypeScript v4.9.4
Node.js v16.19.0
tsc v2.0.4

![image](https://user-images.githubusercontent.com/103377462/211179875-6f8fe986-db87-49bd-8867-d02dd156459b.png)

**Comment by Linux123123** [comment]
`node-fetch` is no longer used in `jspteroapi` and has been replaced by `undici`. I see you are still using the scoped version (`@linux123123/jspteroapi`) instead of the new and updated `jspteroapi` package. To get new updates, please switch the packages.

**Comment by ararouu** [comment]
I was able to fix it anyway by adding "DOM" to my lib in the compiler options.
